PUT http://localhost/api-qr-tandem/v1/change-password.php
Content-Type: "application/json"
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3MjE4MDU3MzEsImV4cCI6MTc1MzM0MTczMSwidXNlcklkIjozLCJlbWFpbCI6ImdlcmVudGVAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIn0.wT0LRXXw3KT97fATKLIkdDJJ-m_Wc3y9Yu91YtT9cd4

{
    "email": "gerente@gmail.com",
    "password": "asdf"
}