PUT http://localhost/api-qr-tandem/v1/change-password.php
Content-Type: "application/json"
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3MjE3MjU4NTIsImV4cCI6MTc1MzI2MTg1MiwidXNlcklkIjo1LCJlbWFpbCI6Imd1ZXN0QGdtYWlsLmNvbSIsInJvbGUiOiJndWVzdCJ9.d9sQytLUDKJEFI_O36BjpiLuKjjbkN_ow4dSBRYOYHk

{
    "email": "guest@gmail.com",
    "password": "12345"
}