
GET http://localhost/api-qr-tandem/v1/list-users.php
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3MTk2NTUyNTgsImV4cCI6MTcxOTY1ODg1OCwidXNlcklkIjoxLCJlbWFpbCI6ImdlcmVudGVAZ21haWwuY29tIn0.bPgXLDs9jnj5bhHINCxGh1TtA_fWlC4BtaW4FAyMD9Y
Content-Type: application/json