GET http://localhost/api-qr-tandem/v1/list-users.php
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3MjE3MjA2ODgsImV4cCI6MTc1MzI1NjY4OCwidXNlcklkIjozLCJlbWFpbCI6ImdlcmVudGVAZ21haWwuY29tIiwicm9sZSI6Imd1ZXN0In0.yCF7mAPTrnh-qDz441qXU3tgwr0QZI-8mB9Gjj3HqJk
Content-Type: "application/json"