
### Obtener la lista de usuarios
GET http://localhost/api-qr-tandem/v1/list-users.php
Accept: application/json

### Obtener la lista de usuarios con encabezado de autorización (si es necesario)
GET http://localhost/api-qr-tandem/v1/list-users.php
Accept: application/json
Authorization: Bearer your_token_here
