POST http://localhost/api-qr-tandem/v1/register-user.php
Content-Type: "application/json"

{
    "nombre": "Penelope González",
    "delegacion":"Aranjuez",
    "email": "penelope@gmail.com",
    "password": "asdf"
}

###
POST http://localhost/api-qr-tandem/v1/register-user.php
Content-Type: "application/json"

{
    "nombre": "Empleado Patrimonio",
    "delegacion":"El Escorial",
    "email": "empleado@gmail.com",
    "password": "asdf"
}
###
POST http://localhost/api-qr-tandem/v1/register-user.php
Content-Type: "application/json"

{
    "nombre": "Invitado Patrimonio",
    "delegacion":"El Escorial",
    "email": "invitado@gmail.com",
    "password": "asdf"
}