POST http://localhost/api-qr-tandem/v1/register-user.php
Content-Type: "application/json"

{
    "nombre": "Gerente Aplicacion",
    "delegacion":"El Escorial",
    "email": "gmail@gmail.com",
    "password": "asdf"
}